const findSolutionByClues = require('./utils/find-solution-by-clues');

const format = matrix =>
    '\r\n' + matrix.map(row => row.join(' ')).join('\r\n') + '\r\n';

process.stdout.write(
    format(
        findSolutionByClues([
            0,
            0,
            0,
            2,
            2,
            0,
            0,
            0,
            0,
            6,
            3,
            0,
            0,
            4,
            0,
            0,
            0,
            0,
            4,
            4,
            0,
            3,
            0,
            0,
        ]),
    ),
);

process.stdout.write(
    format(
        findSolutionByClues([
            3,
            2,
            2,
            3,
            2,
            1,
            1,
            2,
            3,
            3,
            2,
            2,
            5,
            1,
            2,
            2,
            4,
            3,
            3,
            2,
            1,
            2,
            2,
            4,
        ]),
    ),
);

process.stdout.write(
    format(
        findSolutionByClues([
            0,
            3,
            0,
            5,
            3,
            4,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            3,
            0,
            3,
            2,
            3,
            3,
            2,
            0,
            3,
            1,
            0,
        ]),
    ),
);
